[[constraint]]
	name = "github.com/hajimehoshi/ebiten"
	# version = "^1.5.1"
	# branch = "master"
	revision = "71117073d0ff7767588dda407c59028ecdea48cf"

[[constraint]]
	name = "github.com/Bredgren/geo"
	version = "v1.0.0-beta2"
	# branch = "master"
